# Generated by Django 6.0.2 on 2026-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Estimated calorie count for the meal.', null=True),
        ),
    ]
