# Generated by Django 6.0.2 on 2026-03-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_savedrecipe_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='plan_data',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='steps',
        ),
        migrations.CreateModel(
            name='MealPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.mealplan')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=32)),
                ('recipe_title', models.CharField(blank=True, default='', max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.mealplanday')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savedrecipe')),
            ],
            options={
                'ordering': ['day__day_number', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='api.savedrecipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_items', to='api.savedrecipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='mealplanday',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'day_number'), name='uniq_mealplan_day_number'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='uniq_recipe_ingredient_order'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='uniq_recipe_step_order'),
        ),
    ]
