# Generated by Django 6.0.2 on 2026-03-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mealplan_plan_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cooking_skill',
            field=models.CharField(blank=True, default='Intermediate', help_text='Cooking skill level (Beginner, Intermediate, Chef Level).', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_preferences',
            field=models.TextField(blank=True, default='', help_text='Free-text additional preferences.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cuisine_preferences',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of preferred cuisines (e.g. Irish Traditional, Italian).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_restrictions',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of dietary preferences (e.g. Vegan, Halal).'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
