# Generated by Django 6.0.2 on 2026-03-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_cooking_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
