# Generated by Django 6.0.2 on 2026-04-11 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_name_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'meal plan', 'verbose_name_plural': 'meal plans'},
        ),
        migrations.RemoveField(
            model_name='mealplanmeal',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='mealplanmeal',
            name='recipe_title',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='name',
            field=models.CharField(default='My Meal Plan', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='cook_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='prep_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='saved_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plan_slots', to='api.savedrecipe'),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealplanmeal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='mealplanmeal',
            constraint=models.UniqueConstraint(fields=('day', 'meal_type'), name='uniq_day_meal_type'),
        ),
    ]
