# Generated by Django 6.0.2 on 2026-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_meal_plan_relational'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], help_text='Meal type category (breakfast, lunch, dinner).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='cook_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='prep_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
